# enemy_color: "red"
enemy_color: "blue"

# detector
threshold: 300
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

# usb camera
image_width: 1280
image_height: 720
usb_frame_rate: 30

# camera calibrations
camera_matrix: [1320.5372, 0, 633.681963, 0, 1321.02773, 414.417885, 0, 0, 1]
distort_coeffs: [-0.07447857, 0.35185094, 0.00211799, -0.00613892, 1.99027408]